### ISSUE TITLE
Ability to add context to rules or properties

### ISSUE THREAD

**Issue by gavinmcfarland** [limitlessloop/postcss-magic-token#2]
A new format that allows you to provide context about the token.

```css
.a {
    color: tok(concept: feedback, variant: success)
    /* color-feedback-success */
}

.Forms {
    @tok-context group: forms
    .Input {
        border-color: tok()
        /* forms-input-color-border */
    }
}
```
